general:
  ports:
    ldap:  9389
    ldaps: 9636
  id: sds1
  license:
    key: "R2VuZXJpYzotMToxOjCCAacGCSqGSIb3DQEHAqCCAZgwggGUAgEBMQ8wDQYJYIZIAWUDBAIBBQAwGwYJKoZIhvcNAQcBoA4EDEdlbmVyaWM6LTE6MaAAMYIBXTCCAVkCAQEwSDA8MQswCQYDVQQGEwJ1czEMMAoGA1UEChMDaWJtMQ0wCwYDVQQLEwRpc3ZhMRAwDgYDVQQDEwdzaWduaW5nAgh4PC0gxTSNfzANBglghkgBZQMEAgEFAKBpMBgGCSqGSIb3DQEJAzELBgkqhkiG9w0BBwEwHAYJKoZIhvcNAQkFMQ8XDTIyMTAxMDA2NTgyN1owLwYJKoZIhvcNAQkEMSIEICNI9qWOUQ1SXQXNbnOMT5HDinpaosSdz13WyWX2XFLiMA0GCSqGSIb3DQEBAQUABIGARibpp/5rnoMDqO9rOSKFwx3m0bbYGgvkiJtDbHcRHTzErgvxqpYV0NLa9CpsCrzySCxiC2v5Xh4XhkalH6IABYWv+ZWRkh1aen8lshEYR1EAgs8llh3FmQ9xRGTJp1XkacRx3XI/s5dNNtWGEqoc1eX3cCXIG9WvO7Uoxc84b+I="
    accept: standard
  key-stash: B64:EAAAAGF5N3AwSHA4MGtXNm43Z0VhYmNkZWZnaGlqa2zpolze4Rgh9ZRrVSS221Id6aJc3uEYIfWUa1UktttSHVIhG/eeJxSP6aJc3uEYIfWUa1UktttSHVIhG/eeJxSPAroprsc8jYM=
  admin:
    dn: "cn=root"
    pwd: "passw0rd1"
  ssl:
    
    protocols:
    - 'TLS13'
  audit:
    enabled: true
    log-to-file: true
    failure-only: false
    operation:
      add: true
      bind: true
      compare: true
      delete: true
      extended-op: true
      extended-op-event: true
      modify: true
      modify-dn: true
      search: true
      unbind: true
  pwd-encryption: "pbkdf2-sha256"
  pwd-policy:
    enabled: true
    failure-count-interval: 0
    lock-duration: 1800
    lockout: true
    min-length: 6
    max-failures: 5
    advanced:
      no-spaces: true
      no-user-id: true
      login-attribute: uid
      min-lowercase-chars: 1
      min-uppercase-chars: 1
      min-numeric-chars: 1
advanced:
  - attr:
    - name: ibm-slapdSetEnv
      values:
      - 'ibm-slapdPBKDFNumIterations=27500'
    dn: cn=Front End, cn=Configuration
  - attr:
    - name: ibm-slapdUseNonFIPSCrypt
      values:
      - 'TRUE'
    dn: cn=Configuration
  - attr:
    - name: ibm-slapdSetEnv
      values:
      - 'SLAPD_WORKERS=80'
    dn: cn=Front End, cn=Configuration
  - attr:
    - name: ibm-slapdDbConnections
      values:
      - '80'
    dn: cn=Directory,cn=RDBM Backends,cn=IBM Directory,cn=Schemas,cn=Configuration
server:
  suffixes:
  - dn: dc=labtest
    object-classes:
    - domain
  - dn: cn=ibmpolicies
    object-classes:
    - container
  - dn: secAuthority=Default
    object-classes:
    - secAuthorityInfo
    attributes:
    - secAuthority=Default
    - version=6.0
      
  replication:
    admin:
      dn: "cn=replcred"
      pwd: "passw0rd2"